

version: '3.8'

volumes:
   pgdata:

services:
   db:
    image: cloudsec_web
    container_name: jtallas_db_new
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
   
   web:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgresi 
    ports:
      - "5000:5000"

